apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-translator-service
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
spec:
  selector:
    app: {{ template "kube-prometheus-stack.name" . }}-dingtalk-translator
  ports:
    - protocol: TCP
      port: {{ .Values.dingTalk.servicePort }}
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: monitoring
spec:
  selector:
    app: dingtalk-translator
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
