apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dingtalk-translator
  name: translator
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dingtalk-translator
  template:
    metadata:
      labels:
        app: dingtalk-translator
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/senpai/dingtalk-translator:latest
          name: translator
          ports:
            - containerPort: 8000
          env:
          - name: DINGTALK_ACCESS_TOKEN
            value: 19195ef5d3ce080a6966db554d03a348b56cd7c42707deebee51a353fdb2cc7d

---

apiVersion: v1
kind: Service
metadata:
  name: translator-service
  namespace: monitoring
spec:
  selector:
    app: dingtalk-translator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000